# Generated by Django 6.0.3 on 2026-04-28 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم الجوال')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المسدد')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ السداد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'سداد لمورد',
                'verbose_name_plural': 'سداد الموردين',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dabba', models.PositiveIntegerField(default=0, verbose_name='عدد الدبب')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عدد الكيلوات')),
                ('price_per_dabba', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الدبة')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الكيلو')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الشراء')),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الشراء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_purchases', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'عملية شراء من مورد',
                'verbose_name_plural': 'مشتريات الموردين',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
