# Generated by Django 6.0.4 on 2026-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpurchase',
            name='quantity_dabba',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عدد الدبب'),
        ),
    ]
