# Generated by Django 6.0.4 on 2026-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplierpurchase_quantity_dabba'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpurchase',
            name='add_to_inventory',
            field=models.BooleanField(default=False, verbose_name='إضافة الكمية للمخزون'),
        ),
    ]
