# Generated by Django 6.0.4 on 2026-10-01 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_customerpayment'),
        ('suppliers', '0003_supplierpurchase_add_to_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='is_new_accounting_payment',
            field=models.BooleanField(default=False, verbose_name='سداد محاسبي جديد'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='accounting.financialaccount', verbose_name='حساب السداد'),
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='is_new_accounting_purchase',
            field=models.BooleanField(default=False, verbose_name='شراء محاسبي جديد'),
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_purchase_payments', to='accounting.financialaccount', verbose_name='حساب السداد'),
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'مسدد'), ('unpaid', 'آجل')], default='unpaid', max_length=20, verbose_name='حالة السداد'),
        ),
    ]
