# Generated by Django 6.0.3 on 2026-04-07 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0002_remove_sale_purchase_price_per_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale_cash', 'بيع نقدي'), ('expense', 'مصروف'), ('addition', 'إضافة'), ('deduction', 'خصم'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transaction', to='sales.sale', verbose_name='عملية البيع')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workerprofile', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'حركة حساب عامل',
                'verbose_name_plural': 'حركات حسابات العمال',
                'ordering': ['-created_at'],
            },
        ),
    ]
