# Generated by Django 6.0.3 on 2026-04-09 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المصروف')),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('wages', 'أجور ورواتب'), ('transport', 'نقل'), ('maintenance', 'صيانة'), ('electricity', 'كهرباء'), ('other', 'أخرى')], max_length=30, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ المصروف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مصروف تشغيلي',
                'verbose_name_plural': 'المصاريف التشغيلية',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
