# Generated by Django 6.0.4 on 2026-10-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_customerpayment'),
        ('finance', '0002_operatingexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingexpense',
            name='expense_type',
            field=models.CharField(choices=[('operating', 'مصروف تشغيل'), ('personal', 'مصروف شخصي')], default='operating', max_length=20, verbose_name='نوع المصروف'),
        ),
        migrations.AddField(
            model_name='operatingexpense',
            name='is_new_accounting_expense',
            field=models.BooleanField(default=False, verbose_name='مصروف محاسبي جديد'),
        ),
        migrations.AddField(
            model_name='operatingexpense',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.financialaccount', verbose_name='الحساب المالي'),
        ),
    ]
