# Generated by Django 6.0.3 on 2026-04-06 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_dabba_count', models.PositiveIntegerField(default=0, verbose_name='عدد الدبب الكاملة')),
                ('open_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الكيلو المفتوح')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مخزون',
                'verbose_name_plural': 'المخزون',
            },
        ),
    ]
