# Generated by Django 6.0.4 on 2026-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='full_dabba_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عدد الدبب الكاملة'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='open_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الكيلو المفتوح'),
        ),
    ]
