# Generated by Django 6.0.4 on 2026-09-30 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('cashbox', 'صندوق'), ('bank', 'بنك'), ('wallet', 'محفظة'), ('worker', 'عامل')], max_length=20, verbose_name='نوع الحساب')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حساب مالي',
                'verbose_name_plural': 'الحسابات المالية',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'داخل'), ('out', 'خارج')], max_length=3, verbose_name='الاتجاه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('category', models.CharField(max_length=50, verbose_name='التصنيف')),
                ('description', models.CharField(max_length=250, verbose_name='الوصف')),
                ('source_type', models.CharField(max_length=80, verbose_name='نوع المصدر')),
                ('source_id', models.PositiveIntegerField(verbose_name='رقم المصدر')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='معكوس')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounting.financialaccount', verbose_name='الحساب المالي')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'دفتر الحركات',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id', 'is_reversed'], name='accounting__source__a0d946_idx'), models.Index(fields=['account', 'is_reversed'], name='accounting__account_b1476d_idx')],
            },
        ),
    ]
