# Generated by Django 6.0.4 on 2026-10-01 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ التحويل')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='عمولة التحويل')),
                ('description', models.CharField(max_length=250, verbose_name='الوصف')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='accounting.financialaccount', verbose_name='من حساب')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='accounting.financialaccount', verbose_name='إلى حساب')),
            ],
            options={
                'verbose_name': 'تحويل مالي',
                'verbose_name_plural': 'التحويلات المالية',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
