# Generated by Django 6.0.4 on 2026-10-01 03:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_moneytransfer'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ السداد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='accounting.financialaccount', verbose_name='الحساب المالي')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_payments', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'سداد عميل',
                'verbose_name_plural': 'سدادات العملاء',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
