# Generated by Django 6.0.3 on 2026-04-06 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dabba', models.PositiveIntegerField(default=0, verbose_name='عدد الدبب')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='عدد الكيلوات')),
                ('payment_type', models.CharField(choices=[('cash', 'نقد'), ('transfer', 'حوالة'), ('deferred', 'آجل')], max_length=20, verbose_name='نوع الدفع')),
                ('sale_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع للكيلو')),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء للكيلو')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي البيع')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي التكلفة')),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الربح')),
                ('worker_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ النقدي على العامل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البيع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='العميل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='المخزن')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workerprofile', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'المبيعات',
                'ordering': ['-sale_date'],
            },
        ),
    ]
