# Generated by Django 6.0.3 on 2026-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='purchase_price_per_kg',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price_per_kg',
        ),
        migrations.AddField(
            model_name='sale',
            name='price_per_dabba',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الدبة'),
        ),
        migrations.AddField(
            model_name='sale',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الكيلو'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='worker_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='النقد المستلم على العامل'),
        ),
    ]
