# Generated by Django 6.0.4 on 2026-07-16 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('sales', '0002_remove_sale_purchase_price_per_kg_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'سطر بيع', 'verbose_name_plural': 'المبيعات'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_dabba',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عدد الدبب'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عدد الكيلوات'),
        ),
        migrations.CreateModel(
            name='SaleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'نقد'), ('transfer', 'حوالة'), ('deferred', 'آجل')], max_length=20, verbose_name='نوع الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البيع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='العميل')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='المخزن')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workerprofile', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'عمليات البيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.salebatch', verbose_name='عملية البيع'),
        ),
    ]
