# Generated by Django 6.0.4 on 2026-10-01 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_moneytransfer'),
        ('sales', '0003_alter_sale_options_alter_sale_quantity_dabba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_worker_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'worker', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sales', to='accounting.financialaccount', verbose_name='حساب العامل النقدي'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_new_accounting_sale',
            field=models.BooleanField(default=False, verbose_name='بيع محاسبي جديد'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['cashbox', 'bank', 'wallet'], 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_payments', to='accounting.financialaccount', verbose_name='حساب الدفع'),
        ),
    ]
