# Generated by Django 6.0.4 on 2026-10-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_customerpayment'),
        ('sales', '0004_sale_cash_worker_account_sale_is_new_accounting_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.CharField(choices=[('alshahabi', 'الشهابي'), ('samra', 'سمرة')], default='alshahabi', max_length=20, verbose_name='المتجر'),
        ),
        migrations.AddField(
            model_name='salebatch',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ النقد'),
        ),
        migrations.AddField(
            model_name='salebatch',
            name='cash_worker_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'worker', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_cash_sales', to='accounting.financialaccount', verbose_name='حساب النقد'),
        ),
        migrations.AddField(
            model_name='salebatch',
            name='deferred_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الآجل'),
        ),
        migrations.AddField(
            model_name='salebatch',
            name='payment_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['cashbox', 'bank', 'wallet'], 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_transfer_sales', to='accounting.financialaccount', verbose_name='حساب الحوالة'),
        ),
        migrations.AddField(
            model_name='salebatch',
            name='store',
            field=models.CharField(choices=[('alshahabi', 'الشهابي'), ('samra', 'سمرة')], default='alshahabi', max_length=20, verbose_name='المتجر'),
        ),
        migrations.AddField(
            model_name='salebatch',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الحوالة'),
        ),
        migrations.AddField(
            model_name='salebatch',
            name='uses_batch_accounting',
            field=models.BooleanField(default=False, verbose_name='محاسبة على العملية كاملة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقد'), ('transfer', 'حوالة'), ('deferred', 'آجل'), ('mixed', 'مختلط')], max_length=20, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='salebatch',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقد'), ('transfer', 'حوالة'), ('deferred', 'آجل'), ('mixed', 'مختلط')], max_length=20, verbose_name='نوع الدفع'),
        ),
    ]
