# Generated by Django 6.0.3 on 2026-04-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='default_sale_price_per_dabba',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع الافتراضي للدبة'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_sale_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع الافتراضي للكيلو'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الشراء للكيلو'),
        ),
    ]
